language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
env:
  - CI=true
script:
  - node --version
stages:
  - name: npm release
    if: branch = master
  - name: GitHub Release
    if: branch = master
jobs:
  include:
    - stage: npm release
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: 1278588306@qq.com
        api_key: $npm_token
        on:
          tags: true
          branch: master
        tag: latest
        condition: '$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$'
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $github_token
        skip_cleanup: true
        on:
          tags: true
          branch: master
        condition: '$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$'